name: sellio_metrics
description: Sellio Squad â€” Team Metrics Dashboard built with Flutter Web & Hux UI
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  hux: ^0.25.0
  provider: ^6.1.2
  fl_chart: ^0.70.2
  intl: ^0.20.0
  http: ^1.3.0
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
